### ISSUE TITLE
Books trend

### ISSUE THREAD

**Issue by kevinwang09** [priya51096/paper-learningtower#4]
In one of the lines: 

> Furthermore, we see a decline in the score when the category contains more than 500 books, owing to the lack of data in such categories.

But the visualisation with CI did not reflect this. 

Consider rewording.

**Comment by priya51096** [comment]
Thank you, Kevin! I'll rewrite the as per your advice

**Comment by priya51096** [comment]
Hi @kevinwang09 ,

The tibble below shoes the count for each of the book categories

# A tibble: 6 x 2
  book               n
  <fct>          <int>
1 0-10          125583
2 101-200        84750
3 11-25         124194
4 201-500        59168
5 26-100        169222
6 more than 500  33441
